DROP DATABASE IF EXISTS TheBasaboost_SG_Hospital;
CREATE DATABASE TheBasaboost_SG_Hospital;
USE TheBasaboost_SG_Hospital;

------ CREACIÓN DE LA BASE DE DATOS ------
--- TABLAS:
CREATE TABLE MEDICO(
	id_medico SMALLINT PRIMARY KEY IDENTITY,
	nombre VARCHAR(25),
	apellido VARCHAR(25) NOT NULL,
	telefono INT,
	horario VARCHAR(50),
	email VARCHAR(40),
	id_especialidad SMALLINT
);

CREATE TABLE ESPECIALIDAD(
	id_especialidad SMALLINT PRIMARY KEY IDENTITY,
	especialidad VARCHAR(50) NOT NULL
);

CREATE TABLE CITA(
	id_cita INT PRIMARY KEY,
	id_paciente INT NOT NULL,
	id_medico SMALLINT NOT NULL,
	id_estado SMALLINT NOT NULL,
	fecha_hora DATETIME NOT NULL,
);

CREATE TABLE ESTADO_CITA(
	id_estado SMALLINT PRIMARY KEY,
	estado VARCHAR(15) NOT NULL
);

CREATE TABLE RECETA(
	id_receta SMALLINT PRIMARY KEY IDENTITY,
	id_consulta INT,
	id_tratamiento INT,
	instrucciones VARCHAR(200)
);

CREATE TABLE CONSULTA(
	id_consulta INT PRIMARY KEY IDENTITY,
	id_cita INT,
	id_diagnostico INT,
	observaciones VARCHAR(250) NOT NULL,
	fecha_consulta DATE
);

CREATE TABLE DIAGNOSTICO(
	id_diagnostico INT PRIMARY KEY IDENTITY,
	diagnostico VARCHAR(75) NOT NULL
);

-- Intersección Consulta-Receta
CREATE TABLE CONSULTA_RECETA(
   	id_consulta INT NOT NULL,
   	id_receta SMALLINT NOT NULL,
  	PRIMARY KEY (id_consulta, id_receta),
    	FOREIGN KEY (id_consulta) REFERENCES CONSULTA(id_consulta),
    	FOREIGN KEY (id_receta) REFERENCES RECETA(id_receta)
);

CREATE TABLE PACIENTE(
	id_paciente INT PRIMARY KEY,
	nombre VARCHAR(50),
	apellido VARCHAR(50),
	dui VARCHAR(10) NOT NULL,
	fecha_nacimiento DATE,
	direccion VARCHAR(100),
	telefono INT,
	email VARCHAR(70),
	fecha_registro DATE,
	id_historial_medico INT
);

CREATE TABLE TRATAMIENTO(
	id_tratamiento INT PRIMARY KEY IDENTITY,
	duracion VARCHAR(20) NOT NULL,
	id_medicamento INT NOT NULL,
	id_dosis INT NOT NULL
);

CREATE TABLE MEDICAMENTO(
	id_medicamento INT PRIMARY KEY,
	medicamento VARCHAR(50)
);

CREATE TABLE DOSIS(
	id_dosis INT PRIMARY KEY,
	dosis VARCHAR(50)
);

CREATE TABLE HISTORIAL_MEDICO(
	id_historial_medico INT PRIMARY KEY,
	id_paciente INT,
	id_alergias SMALLINT,
	id_enfermedades_cronicas SMALLINT,
	antecedentes_familiares VARCHAR(200),
	fecha_registro DATE
);

CREATE TABLE ALERGIAS(
	id_alergias SMALLINT PRIMARY KEY,
	alergias VARCHAR(50)
);

CREATE TABLE ENFERMEDADES_CRONICAS(
	id_enfermedades_cronicas SMALLINT PRIMARY KEY,
	enfermedad_cronica VARCHAR(50)
);

-- FOREIGN KEYS:
-- PARA LA TABLA "MEDICO"
ALTER TABLE MEDICO ADD FOREIGN KEY(id_especialidad) REFERENCES ESPECIALIDAD(id_especialidad);

-- PARA LA TABLA "CITA"
ALTER TABLE CITA ADD FOREIGN KEY(id_paciente) REFERENCES PACIENTE(id_paciente);
ALTER TABLE CITA ADD FOREIGN KEY(id_medico) REFERENCES MEDICO(id_medico);
ALTER TABLE CITA ADD FOREIGN KEY(id_estado) REFERENCES ESTADO_CITA(id_estado);

-- PARA LA TABLA "RECETA"
ALTER TABLE RECETA ADD FOREIGN KEY(id_consulta) REFERENCES CONSULTA(id_consulta);
ALTER TABLE RECETA ADD FOREIGN KEY(id_tratamiento) REFERENCES TRATAMIENTO(id_tratamiento);

-- PARA LA TABLA INTERMEDIA "CONSULTA_RECETA"
ALTER TABLE CONSULTA_RECETA ADD FOREIGN KEY (id_consulta) REFERENCES CONSULTA(id_consulta) ON DELETE CASCADE;
ALTER TABLE CONSULTA_RECETA ADD FOREIGN KEY (id_receta) REFERENCES RECETA(id_receta) ON DELETE CASCADE;

-- PARA LA TABLA "CONSULTA"
ALTER TABLE CONSULTA ADD FOREIGN KEY(id_cita) REFERENCES CITA(id_cita);
ALTER TABLE CONSULTA ADD FOREIGN KEY(id_diagnostico) REFERENCES DIAGNOSTICO(id_diagnostico);

-- PARA LA TABLA "PACIENTE"
ALTER TABLE PACIENTE ADD FOREIGN KEY(id_historial_medico) REFERENCES HISTORIAL_MEDICO(id_historial_medico);

-- PARA LA TABLA "TRATAMIENTO"
ALTER TABLE TRATAMIENTO ADD FOREIGN KEY(id_medicamento) REFERENCES MEDICAMENTO(id_medicamento);
ALTER TABLE TRATAMIENTO ADD FOREIGN KEY(id_dosis) REFERENCES DOSIS(id_dosis);

-- PARA LA TABLA "HISTORIAL_MEDICO"
ALTER TABLE HISTORIAL_MEDICO ADD FOREIGN KEY(id_paciente) REFERENCES PACIENTE(id_paciente);
ALTER TABLE HISTORIAL_MEDICO ADD FOREIGN KEY(id_alergias) REFERENCES ALERGIAS(id_alergias);
ALTER TABLE HISTORIAL_MEDICO ADD FOREIGN KEY(id_enfermedades_cronicas) REFERENCES ENFERMEDADES_CRONICAS(id_enfermedades_cronicas);

-- Inserciones y poblamiento de la BD

INSERT INTO ESPECIALIDAD (especialidad) VALUES
('Medicina interna'),
('Pediatría'),
('Cardiología'),
('Neurología'),
('Ginecología y Obstetricia'),
('Ortopedia y Traumatología'),
('Cirugía general'),
('Dermatología'),
('Oftalmología'),
('Otorrinolaringología'),
('Psiquiatría'),
('Endocrinología'),
('Urología'),
('Nefrología'),
('Gastroenterología'),
('Neumología'),
('Oncología'),
('Reumatología'),
('Anestesiología'),
('Emergenciología');

INSERT INTO alergias (alergias) VALUES
('Penicilina'),
('Polen'),
('Lácteos'),
('Mariscos'),
('Gluten'),
('Huevo'),
('Frutos secos'),
('Aspirina'),
('Sulfas'),
('Picaduras de abeja'),
('Latex'),
('Polvo'),
('Animales domésticos'),
('Moho'),
('Antiinflamatorios'),
('Colorantes alimentarios'),
('Cacahuate'),
('Soja'),
('Cítricos'),
('Medicamentos antiinflamatorios no esteroideos'),
('Perfumes'),
('Cloro'),
('Cosméticos'),
('Vacunas'),
('Plumas'),
('Fresas'),
('Otros');

INSERT INTO enfermedades_cronicas (enfermedad_cronica) VALUES
('Diabetes mellitus'),
('Hipertensión arterial'),
('Asma'),
('Epoc'),
('Insuficiencia cardíaca'),
('Insuficiencia renal crónica'),
('Artritis reumatoide'),
('Lupus'),
('Enfermedad de crohn'),
('Colitis ulcerativa'),
('Epilepsia'),
('Enfermedad de parkinson'),
('Alzheimer'),
('Cáncer'),
('Fibromialgia'),
('Osteoporosis'),
('Migraña crónica'),
('Enfermedad coronaria'),
('Hipotiroidismo'),
('Hipertiroidismo'),
('Obesidad'),
('Hipercolesterolemia'),
('Trastorno bipolar'),
('Depresión mayor'),
('Trastorno obsesivo compulsivo'),
('Esquizofrenia'),
('Psoriasis'),
('Dermatitis atópica'),
('Esofagitis crónica'),
('Cirrosis hepática'),
('Hepatitis b crónica'),
('Hepatitis c crónica'),
('Anemia crónica'),
('Glaucoma'),
('Cataratas crónicas'),
('Insuficiencia venosa crónica'),
('Esclerosis múltiple'),
('Gota'),
('Valvulopatía'),
('Arritmia crónica');

INSERT INTO estado_cita (estado) VALUES
('Pendiente'),
('Atendida'),
('Cancelada'),
('Reprogramada'),
('No asistió'),
('Confirmada'),
('En sala de espera'),
('En consulta'),
('Finalizada'),
('En proceso de pago'),
('Cita por teléfono'),
('Cita virtual'),
('Urgente'),
('Derivada'),
('En revisión');

INSERT INTO diagnostico (diagnostico) VALUES
('Infección respiratoria aguda'),
('Gripe'),
('Faringitis'),
('Bronquitis'),
('Neumonía'),
('Asma aguda'),
('Epoc descompensado'),
('Insuficiencia cardíaca aguda'),
('Angina de pecho'),
('Infarto agudo de miocardio'),
('Arritmia'),
('Hipertensión arterial'),
('Diabetes mellitus tipo 2'),
('Hipoglucemia'),
('Gastroenteritis aguda'),
('Diarrea'),
('Colitis'),
('Úlcera gástrica'),
('Reflujo gastroesofágico'),
('Hepatitis viral'),
('Cirrosis hepática'),
('Colecistitis'),
('Apendicitis aguda'),
('Cólico renal'),
('Infección de vías urinarias'),
('Cistitis'),
('Pielonefritis'),
('Litiasis renal'),
('Insuficiencia renal crónica'),
('Artritis'),
('Artrosis'),
('Lumbalgia'),
('Cervicalgia'),
('Migraña'),
('Cefalea tensional'),
('Epilepsia'),
('Accidente cerebrovascular'),
('Parkinson'),
('Alzheimer'),
('Anemia ferropénica'),
('Leucemia'),
('Linfoma'),
('Psoriasis'),
('Dermatitis atópica'),
('Alergia respiratoria'),
('Urticaria'),
('Conjuntivitis'),
('Otitis media'),
('Sinusitis'),
('Rinitis alérgica'),
('Otalgia'),
('Hernia discal'),
('Esguince de tobillo'),
('Fractura de radio'),
('Fractura de fémur'),
('Traumatismo craneoencefálico'),
('Herida cortante'),
('Quemadura leve'),
('Obesidad'),
('Desnutrición'),
('Trastorno de ansiedad'),
('Depresión mayor'),
('Trastorno bipolar'),
('Esquizofrenia'),
('Trastorno obsesivo compulsivo'),
('Trastorno del sueño'),
('Embarazo normal'),
('Embarazo de alto riesgo'),
('Preeclampsia'),
('Diabetes gestacional'),
('Infección urinaria en embarazo'),
('Parto vaginal'),
('Cesárea'),
('Amenorrea'),
('Dislipidemia'),
('Hipercolesterolemia'),
('Hipotiroidismo'),
('Hipertiroidismo'),
('Valvulopatía'),
('Enfermedad pulmonar intersticial'),
('Fibromialgia'),
('Gota'),
('Dermatitis seborreica'),
('Apendicitis crónica'),
('Anemia crónica'),
('Trastorno de pánico'),
('Neumotórax'),
('Peritonitis'),
('Meningitis'),
('Otitis externa'),
('Cáncer de pulmón'),
('Cáncer de mama'),
('Cáncer de colon'),
('Cáncer gástrico'),
('Cáncer de próstata'),
('Cáncer de hígado'),
('Cáncer de páncreas'),
('Cáncer de ovario'),
('Cáncer de vejiga'),
('Cáncer de riñón'),
('Cáncer de piel'),
('Cáncer de tiroides'),
('Cáncer de útero'),
('Cáncer de testículo'),
('Cáncer de laringe'),
('Cáncer de esófago'),
('Cáncer de cerebro'),
('Cáncer de hueso'),
('Cáncer de sangre'),
('Cáncer de linfa'),
('Sepsis'),
('Shock séptico'),
('Shock cardiogénico'),
('Shock hipovolémico'),
('Síncope'),
('Eclampsia'),
('Endometriosis'),
('Mioma uterino'),
('Quiste ovárico'),
('Hiperplasia prostática benigna'),
('Esclerosis múltiple'),
('Esclerosis lateral amiotrófica'),
('Distrofia muscular'),
('Síndrome de guillain-barré'),
('Polineuropatía'),
('Glomerulonefritis'),
('Nefritis intersticial'),
('Nefropatía diabética'),
('Insuficiencia hepática'),
('Enfermedad celíaca'),
('Pancreatitis aguda'),
('Pancreatitis crónica'),
('Enfermedad de crohn'),
('Colitis ulcerativa'),
('Hemorroides'),
('Fisura anal'),
('Fístula anal'),
('Absceso perianal'),
('Varices esofágicas'),
('Enfermedad de ménière'),
('Hipoacusia'),
('Cataratas'),
('Glaucoma'),
('Desprendimiento de retina'),
('Retinopatía diabética'),
('Trombosis venosa profunda'),
('Tromboflebitis'),
('Trombosis arterial'),
('Infarto cerebral'),
('Hemorragia cerebral'),
('Hematoma subdural'),
('Hematoma epidural'),
('Hematoma intracerebral'),
('Meningioma'),
('Absceso cerebral'),
('Enfermedad pulmonar obstructiva crónica'),
('Bronquiolitis'),
('Tuberculosis pulmonar'),
('Tuberculosis extrapulmonar'),
('Pleuritis'),
('Derrame pleural'),
('Neumotórax espontáneo'),
('Aspergilosis pulmonar'),
('Histoplasmosis'),
('Silicosis'),
('Sarcoidosis'),
('Fibrosis pulmonar'),
('Hipertensión pulmonar'),
('Cardiopatía congénita'),
('Prolapso de válvula mitral'),
('Insuficiencia mitral'),
('Insuficiencia aórtica'),
('Estenosis aórtica'),
('Estenosis mitral'),
('Endocarditis'),
('Pericarditis'),
('Miocarditis'),
('Taquicardia paroxística supraventricular'),
('Bradicardia'),
('Síndrome de apnea del sueño'),
('Síndrome metabólico'),
('Hipertrigliceridemia'),
('Enfermedad de addison'),
('Síndrome de cushing'),
('Feocromocitoma'),
('Insuficiencia suprarrenal'),
('Hipercalcemia'),
('Hipocalcemia'),
('Hipopotasemia'),
('Hiperpotasemia'),
('Síndrome nefrótico'),
('Síndrome nefrítico'),
('Enfermedad de graves'),
('Enfermedad de hashimoto'),
('Deficiencia de vitamina d'),
('Deficiencia de vitamina b12'),
('Deficiencia de hierro'),
('Escorbuto'),
('Raquitismo'),
('Osteomalacia'),
('Osteoporosis avanzada'),
('Luxación de hombro'),
('Luxación de cadera'),
('Esguince cervical'),
('Esguince lumbar'),
('Traumatismo facial'),
('Fractura de costilla'),
('Fractura de tibia'),
('Fractura de clavícula'),
('Fractura de pelvis'),
('Fractura vertebral'),
('Contusión cerebral'),
('Hemorragia digestiva alta'),
('Hemorragia digestiva baja'),
('Anorexia nerviosa'),
('Bulimia nerviosa'),
('Trastorno por déficit de atención'),
('Trastorno del espectro autista'),
('Síndrome de asperger'),
('Enfermedad de meniere'),
('Acné severo'),
('Verrugas'),
('Herpes zóster'),
('Herpes simple'),
('Varicela'),
('Sarampión'),
('Rubeola'),
('Paperas'),
('Escarlatina'),
('Tos ferina'),
('Dengue'),
('Zika'),
('Chikungunya'),
('Paludismo'),
('Leishmaniasis'),
('Filariasis'),
('Teniasis'),
('Cisticercosis');

INSERT INTO medicamento (medicamento) VALUES
('Paracetamol'),
('Ibuprofeno'),
('Amoxicilina'),
('Ceftriaxona'),
('Azitromicina'),
('Metformina'),
('Insulina'),
('Enalapril'),
('Losartán'),
('Amlodipina'),
('Furosemida'),
('Omeprazol'),
('Ranitidina'),
('Lansoprazol'),
('Simvastatina'),
('Atorvastatina'),
('Rosuvastatina'),
('Clopidogrel'),
('Aspirina'),
('Warfarina'),
('Heparina'),
('Enoxaparina'),
('Metoprolol'),
('Carvedilol'),
('Propranolol'),
('Bisoprolol'),
('Digoxina'),
('Levofloxacino'),
('Ciprofloxacino'),
('Doxiciclina'),
('Clindamicina'),
('Penicilina'),
('Ampicilina'),
('Gentamicina'),
('Vancomicina'),
('Meropenem'),
('Imipenem'),
('Piperacilina tazobactam'),
('Sulfametoxazol trimetoprima'),
('Nitrofurantoína'),
('Fluconazol'),
('Itraconazol'),
('Ketoconazol'),
('Voriconazol'),
('Aciclovir'),
('Oseltamivir'),
('Ribavirina'),
('Lamivudina'),
('Tenofovir'),
('Lopinavir ritonavir'),
('Zidovudina'),
('Efavirenz'),
('Sofosbuvir'),
('Interferón alfa'),
('Prednisona'),
('Dexametasona'),
('Hidrocortisona'),
('Betametasona'),
('Mometasona'),
('Clobetasol'),
('Beclometasona'),
('Montelukast'),
('Salbutamol'),
('Bromuro de ipratropio'),
('Tiotropio'),
('Teofilina'),
('Codeína'),
('Morfina'),
('Tramadol'),
('Fentanilo'),
('Oxicodona'),
('Metadona'),
('Gabapentina'),
('Pregabalina'),
('Carbamazepina'),
('Fenitoína'),
('Ácido valproico'),
('Lamotrigina'),
('Levetiracetam'),
('Topiramato'),
('Clonazepam'),
('Diazepam'),
('Alprazolam'),
('Midazolam'),
('Lorazepam'),
('Risperidona'),
('Olanzapina'),
('Quetiapina'),
('Aripiprazol'),
('Haloperidol'),
('Sertralina'),
('Fluoxetina'),
('Paroxetina'),
('Escitalopram'),
('Amitriptilina'),
('Nortriptilina'),
('Duloxetina'),
('Venlafaxina'),
('Mirtazapina'),
('Bupropión'),
('Lithium'),
('Clorpromazina'),
('Sulpirida'),
('Tiaprida'),
('Valproato de magnesio'),
('Acido acetilsalicílico'),
('Diclofenaco'),
('Naproxeno'),
('Meloxicam'),
('Celecoxib'),
('Etoricoxib'),
('Colchicina'),
('Alopurinol'),
('Febuxostat'),
('Metotrexato'),
('Azatioprina'),
('Ciclosporina'),
('Tacrolimus'),
('Micofenolato mofetil'),
('Sulfasalazina'),
('Hidroxicloroquina'),
('Infliximab'),
('Adalimumab'),
('Etanercept'),
('Insulina glargina'),
('Insulina NPH'),
('Insulina lispro'),
('Glibenclamida'),
('Gliclazida'),
('Repaglinida'),
('Sitagliptina'),
('Linagliptina'),
('Vildagliptina'),
('Canagliflozina'),
('Dapagliflozina'),
('Empagliflozina'),
('Pioglitazona'),
('Rosiglitazona'),
('Ezetimiba'),
('Gemfibrozilo'),
('Fenofibrato'),
('Eritropoyetina'),
('Hierro oral'),
('Hierro intravenoso'),
('Ácido fólico'),
('Cianocobalamina'),
('Calcio'),
('Vitamina d'),
('Vitamina b12'),
('Complejo b'),
('Vitamina c'),
('Multivitamínico'),
('Cloruro de potasio'),
('Cloruro de sodio'),
('Gluconato de calcio'),
('Bicarbonato de sodio'),
('Alopurinol'),
('Mebendazol'),
('Albendazol'),
('Metronidazol'),
('Tinidazol'),
('Cloroquina'),
('Primaquina'),
('Ivermectina'),
('Praziquantel'),
('Niclosamida'),
('Rifampicina'),
('Isoniazida'),
('Pirazinamida'),
('Etambutol'),
('Estreptomicina'),
('Cicloserina'),
('Amikacina'),
('Kanamicina'),
('Claritromicina'),
('Eritromicina'),
('Azitromicina suspensión'),
('Cefalexina'),
('Cefuroxima'),
('Cefepima'),
('Ceftazidima'),
('Cefotaxima'),
('Cefazolina'),
('Ampicilina sulbactam'),
('Amoxicilina clavulanato'),
('Piperacilina'),
('Tazobactam'),
('Linezolid'),
('Tigeciclina'),
('Daptomicina'),
('Cloranfenicol'),
('Tobramicina'),
('Cotrimoxazol'),
('Nistatina'),
('Griseofulvina'),
('Terbinafina'),
('Clotrimazol'),
('Miconazol'),
('Ketotifeno'),
('Loratadina'),
('Desloratadina'),
('Cetirizina'),
('Fexofenadina'),
('Hidroxicina'),
('Montelukast granulado'),
('Albuterol'),
('Formoterol'),
('Budesonida'),
('Fluticasona'),
('Salbutamol inhalador'),
('Salmeterol'),
('Xantina'),
('Difenhidramina'),
('Prometazina'),
('Ondansetrón'),
('Metoclopramida'),
('Domperidona'),
('Butilhioscina'),
('Hioscina'),
('Loperamida'),
('Racecadotrilo'),
('Budesonida nebulizable'),
('Sulfato ferroso'),
('Polietilenglicol'),
('Bisacodilo');

INSERT INTO dosis (dosis) VALUES
('500 mg'),
('250 mg'),
('100 mg'),
('50 mg'),
('25 mg'),
('10 mg'),
('5 mg'),
('1 g'),
('2 g'),
('3 g'),
('4 g'),
('500 mcg'),
('100 mcg'),
('200 mcg'),
('400 mcg'),
('800 mcg'),
('2 ml'),
('5 ml'),
('10 ml'),
('20 ml'),
('40 ml'),
('100 ml'),
('250 ml'),
('500 ml'),
('1 l'),
('1 tableta diaria'),
('1 tableta cada 12 horas'),
('1 tableta cada 8 horas'),
('1 tableta cada 24 horas'),
('1 tableta cada 6 horas'),
('2 tabletas al día'),
('2 tabletas cada 8 horas'),
('1 cápsula diaria'),
('1 cápsula cada 12 horas'),
('1 cápsula cada 8 horas'),
('1 cápsula cada 24 horas'),
('2 cápsulas al día'),
('1 ampolla'),
('2 ampollas'),
('3 ampollas'),
('1 gota'),
('2 gotas'),
('3 gotas'),
('4 gotas'),
('5 gotas'),
('10 gotas'),
('20 gotas'),
('30 gotas'),
('5 ml cada 12 horas'),
('5 ml cada 8 horas'),
('5 ml cada 6 horas'),
('10 ml cada 12 horas'),
('10 ml cada 8 horas'),
('10 ml cada 6 horas'),
('15 ml cada 8 horas'),
('20 ml cada 12 horas'),
('20 ml cada 8 horas'),
('30 ml cada 12 horas'),
('30 ml cada 8 horas'),
('100 mg cada 8 horas'),
('100 mg cada 12 horas'),
('250 mg cada 8 horas'),
('250 mg cada 12 horas'),
('500 mg cada 8 horas'),
('500 mg cada 12 horas'),
('1 inhalación'),
('2 inhalaciones'),
('1 nebulización'),
('2 nebulizaciones al día'),
('1 parche diario'),
('1 parche cada 72 horas'),
('1 supositorio'),
('2 supositorios'),
('1 óvulo'),
('2 óvulos'),
('Aplicar capa fina'),
('Aplicar dos veces al día'),
('Aplicar tres veces al día'),
('Aplicar cada 12 horas'),
('Aplicar cada 8 horas'),
('Aplicar cada 24 horas'),
('1 sobre cada 24 horas'),
('1 sobre cada 12 horas'),
('1 sobre cada 8 horas'),
('1 vial'),
('2 viales'),
('1 pastilla cada 8 horas'),
('1 pastilla cada 12 horas'),
('1 pastilla cada 24 horas'),
('1 pastilla diaria'),
('2 pastillas al día'),
('0.5 mg'),
('0.25 mg'),
('0.1 mg'),
('60 mg'),
('75 mg'),
('150 mg'),
('300 mg'),
('600 mg'),
('900 mg'),
('1200 mg'),
('1800 mg'),
('1 puff cada 12 horas'),
('1 puff cada 24 horas'),
('2 puff cada 12 horas'),
('2 puff cada 24 horas'),
('1 dosis única'),
('Dosis inicial'),
('Dosis de mantenimiento'),
('Dosis máxima'),
('Dosis pediátrica'),
('Dosis adulto'),
('Dosis ajustada a peso'),
('Dosis ajustada a edad'),
('0.05 mg'),
('0.03 mg'),
('0.015 mg'),
('0.0075 mg'),
('20 mg'),
('30 mg'),
('40 mg'),
('80 mg'),
('160 mg'),
('320 mg'),
('480 mg'),
('960 mg'),
('12 mg'),
('24 mg'),
('36 mg'),
('48 mg'),
('60 mg cada 12 horas'),
('75 mg cada 12 horas'),
('100 mg cada 24 horas'),
('250 mg cada 24 horas'),
('500 mg cada 24 horas'),
('Infusión continua'),
('Bolo intravenoso'),
('Inyección subcutánea'),
('Inyección intramuscular'),
('Inyección intravenosa'),
('Vía oral'),
('Vía tópica'),
('Vía inhalatoria'),
('Vía rectal'),
('Vía vaginal'),
('Vía oftálmica'),
('Vía nasal'),
('Vía sublingual');

INSERT INTO tratamiento (duracion, id_medicamento, id_dosis) VALUES
('5 días', 1, 1),
('7 días', 2, 2),
('10 días', 3, 3),
('14 días', 4, 4),
('30 días', 5, 5),
('1 mes', 6, 6),
('2 meses', 7, 7),
('1 día', 8, 8),
('2 días', 9, 9),
('3 días', 10, 10),
('15 días', 11, 11),
('21 días', 12, 12),
('4 días', 13, 13),
('6 días', 14, 14),
('12 días', 15, 15),
('20 días', 16, 16),
('9 días', 17, 17),
('18 días', 18, 18),
('24 horas', 19, 19),
('72 horas', 20, 20),
('1 semana', 21, 21),
('2 semanas', 22, 22),
('3 semanas', 23, 23),
('4 semanas', 24, 24),
('1 año', 25, 25),
('Dosis única', 26, 26),
('Tratamiento continuo', 27, 27),
('Uso según indicación', 28, 28),
('Dosis diaria', 29, 29),
('Dosis semanal', 30, 30),
('Dosis mensual', 31, 31),
('Cada 8 horas', 32, 32),
('Cada 12 horas', 33, 33),
('Cada 24 horas', 34, 34),
('Cada 6 horas', 35, 35),
('Antes de dormir', 36, 36),
('En ayunas', 37, 37),
('Después de comer', 38, 38),
('Durante 4 semanas', 39, 39),
('Durante 8 semanas', 40, 40),
('Cada 48 horas', 41, 41),
('Cada 72 horas', 42, 42),
('Durante 3 meses', 43, 43),
('Durante 6 meses', 44, 44),
('Cada 2 días', 45, 45),
('Durante el embarazo', 46, 46),
('Durante lactancia', 47, 47),
('Según necesidad', 48, 48),
('En caso de dolor', 49, 49),
('Según síntomas', 50, 50),
('5 días', 51, 51),
('7 días', 52, 52),
('10 días', 53, 53),
('14 días', 54, 54),
('30 días', 55, 55),
('1 mes', 56, 56),
('2 meses', 57, 57),
('1 día', 58, 58),
('2 días', 59, 59),
('3 días', 60, 60),
('15 días', 61, 61),
('21 días', 62, 62),
('4 días', 63, 63),
('6 días', 64, 64),
('12 días', 65, 65),
('20 días', 66, 66),
('9 días', 67, 67),
('18 días', 68, 68),
('24 horas', 69, 69),
('72 horas', 70, 70),
('1 semana', 71, 71),
('2 semanas', 72, 72),
('3 semanas', 73, 73),
('4 semanas', 74, 74),
('1 año', 75, 75),
('Dosis única', 76, 76),
('Tratamiento continuo', 77, 77),
('Uso según indicación', 78, 78),
('Dosis diaria', 79, 79),
('Dosis semanal', 80, 80),
('Dosis mensual', 81, 81),
('Cada 8 horas', 82, 82),
('Cada 12 horas', 83, 83),
('Cada 24 horas', 84, 84),
('Cada 6 horas', 85, 85),
('Antes de dormir', 86, 86),
('En ayunas', 87, 87),
('Después de comer', 88, 88),
('Durante 4 semanas', 89, 89),
('Durante 8 semanas', 90, 90),
('Cada 48 horas', 91, 91),
('Cada 72 horas', 92, 92),
('Durante 3 meses', 93, 93),
('Durante 6 meses', 94, 94),
('Cada 2 días', 95, 95),
('Durante el embarazo', 96, 96),
('Durante lactancia', 97, 97),
('Según necesidad', 98, 98),
('En caso de dolor', 99, 99),
('Según síntomas', 100, 100),
('5 días', 101, 101),
('7 días', 102, 102),
('10 días', 103, 103),
('14 días', 104, 104),
('30 días', 105, 105),
('1 mes', 106, 106),
('2 meses', 107, 107),
('1 día', 108, 108),
('2 días', 109, 109),
('3 días', 110, 110),
('15 días', 111, 111),
('21 días', 112, 112),
('4 días', 113, 113),
('6 días', 114, 114),
('12 días', 115, 115),
('20 días', 116, 116),
('9 días', 117, 117),
('18 días', 118, 118),
('24 horas', 119, 119),
('72 horas', 120, 120),
('1 semana', 121, 121),
('2 semanas', 122, 122),
('3 semanas', 123, 123),
('4 semanas', 124, 124),
('1 año', 125, 125),
('Dosis única', 126, 126),
('Tratamiento continuo', 127, 127),
('Uso según indicación', 128, 128),
('Dosis diaria', 129, 129),
('Dosis semanal', 130, 130),
('Dosis mensual', 131, 131),
('Cada 8 horas', 132, 132),
('Cada 12 horas', 133, 133),
('Cada 24 horas', 134, 134),
('Cada 6 horas', 135, 135),
('Antes de dormir', 136, 136),
('En ayunas', 137, 137),
('Después de comer', 138, 138),
('Durante 4 semanas', 139, 139),
('Durante 8 semanas', 140, 140),
('Cada 48 horas', 141, 141),
('Cada 72 horas', 142, 142),
('Durante 3 meses', 143, 143),
('Durante 6 meses', 144, 144),
('Cada 2 días', 145, 145),
('Durante el embarazo', 146, 1),
('Durante lactancia', 147, 2),
('Según necesidad', 148, 3),
('En caso de dolor', 149, 4),
('Según síntomas', 150, 5),
('5 días', 151, 6),
('7 días', 152, 7),
('10 días', 153, 8),
('14 días', 154, 9),
('30 días', 155, 10),
('1 mes', 156, 11),
('2 meses', 157, 12),
('1 día', 158, 13),
('2 días', 159, 14),
('3 días', 160, 15),
('15 días', 161, 16),
('21 días', 162, 17),
('4 días', 163, 18),
('6 días', 164, 19),
('12 días', 165, 20),
('20 días', 166, 21),
('9 días', 167, 22),
('18 días', 168, 23),
('24 horas', 169, 24),
('72 horas', 170, 25),
('1 semana', 171, 26),
('2 semanas', 172, 27),
('3 semanas', 173, 28),
('4 semanas', 174, 29),
('1 año', 175, 30),
('Dosis única', 176, 31),
('Tratamiento continuo', 177, 32),
('Uso según indicación', 178, 33),
('Dosis diaria', 179, 34),
('Dosis semanal', 180, 35),
('Dosis mensual', 181, 36),
('Cada 8 horas', 182, 37),
('Cada 12 horas', 183, 38),
('Cada 24 horas', 184, 39),
('Cada 6 horas', 185, 40),
('Antes de dormir', 186, 41),
('En ayunas', 187, 42),
('Después de comer', 188, 43),
('Durante 4 semanas', 189, 44),
('Durante 8 semanas', 190, 45),
('Cada 48 horas', 191, 46),
('Cada 72 horas', 192, 47),
('Durante 3 meses', 193, 48),
('Durante 6 meses', 194, 49),
('Cada 2 días', 195, 50),
('Durante el embarazo', 196, 51),
('Durante lactancia', 197, 52),
('Según necesidad', 198, 53),
('En caso de dolor', 199, 54),
('Según síntomas', 200, 55),
('Tratamiento prolongado', 201, 56),
('Dosis alterna', 202, 57),
('Bajo indicación médica', 203, 58),
('Con ajuste renal', 204, 59),
('Con ajuste hepático', 205, 60),
('Cada 4 horas', 206, 61),
('Solo si persisten síntomas', 207, 62),
('Durante crisis', 208, 63),
('Hasta remisión', 209, 64);
